language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
  - hhvm
 
matrix:
    allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - mysql -e 'create database OWASP;'
  - mysql OWASP < SQL/OWASP.sql
  - psql -c 'create database OWASP;' -U postgres
  - composer install --dev --no-interaction
  - cp libs/config.sample.php libs/config.php

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

