language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - hhvm
  - hhvm-nightly

matrix:
    allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - travis_retry composer self-update
  - mysql -e 'create database OWASP;'
  - mysql OWASP < SQL/OWASP.sql
  - psql -c 'create database "OWASP";' -U postgres
  - travis_retry composer install --no-interaction
  - cp libs/config.sample.php libs/config.php

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

